export const catalogo = [
  {
    id: "1",
    marca: "KitKat",
    nome: "Abacaxi",
    preco: 3,
    imagem: "./brasil/abacaxi.png",
    japones: false,
  },
  {
    id: "2",
    marca: "KitKat",
    nome: "Algodão Doce",
    preco: 3,
    imagem: "./brasil/algodao-doce.png",
    japones: false,
  },
  {
    id: "3",
    marca: "KitKat",
    nome: "Ao Leite",
    preco: 3,
    imagem: "./brasil/ao-leite.png",
    japones: false,
  },
  {
    id: "4",
    marca: "KitKat",
    nome: "Avelã",
    preco: 3,
    imagem: "./brasil/avela.png",
    japones: false,
  },
  {
    id: "5",
    marca: "KitKat",
    nome: "Banana",
    preco: 3,
    imagem: "./brasil/banana.png",
    japones: false,
  },
  {
    id: "6",
    marca: "KitKat",
    nome: "Café",
    preco: 3,
    imagem: "./brasil/cafe.png",
    japones: false,
  },
  {
    id: "7",
    marca: "KitKat",
    nome: "Churros",
    preco: 3,
    imagem: "./brasil/churros.png",
    japones: false,
  },
  {
    id: "8",
    marca: "KitKat",
    nome: "Coco",
    preco: 3,
    imagem: "./brasil/coco.png",
    japones: false,
  },
  {
    id: "9",
    marca: "KitKat",
    nome: "Dark",
    preco: 3,
    imagem: "./brasil/dark.png",
    japones: false,
  },
  {
    id: "10",
    marca: "KitKat",
    nome: "Framboesa",
    preco: 3,
    imagem: "./brasil/framboesa.png",
    japones: false,
  },
  {
    id: "11",
    marca: "KitKat",
    nome: "Goiaba",
    preco: 3,
    imagem: "./brasil/goiaba.png",
    japones: false,
  },
  {
    id: "12",
    marca: "KitKat",
    nome: "Limão",
    preco: 3,
    imagem: "./brasil/limao.png",
    japones: false,
  },
  {
    id: "13",
    marca: "KitKat",
    nome: "Maracúja",
    preco: 3,
    imagem: "./brasil/maracuja.png",
    japones: false,
  },
  {
    id: "14",
    marca: "KitKat",
    nome: "Menta",
    preco: 3,
    imagem: "./brasil/menta.png",
    japones: false,
  },
  {
    id: "15",
    marca: "KitKat",
    nome: "Morango",
    preco: 3,
    imagem: "./brasil/morango.png",
    japones: false,
  },
  {
    id: "16",
    marca: "KitKat",
    nome: "Pistache",
    preco: 3,
    imagem: "./brasil/pistache.png",
    japones: false,
  },
  {
    id: "17",
    marca: "KitKat",
    nome: "White",
    preco: 3,
    imagem: "./brasil/white.png",
    japones: false,
  },
  {
    id: "18",
    marca: "KitKat",
    nome: "Classic",
    preco: 30,
    imagem: "./japao/classic.png",
    japones: true,
  },
  {
    id: "19",
    marca: "KitKat",
    nome: "Marcha",
    preco: 40,
    imagem: "./japao/matcha.png",
    japones: true,
  },
  {
    id: "20",
    marca: "KitKat",
    nome: "Mojicha",
    preco: 40,
    imagem: "./japao/mojicha.png",
    japones: true,
  },
  {
    id: "21",
    marca: "KitKat",
    nome: "Trigo Integral",
    preco: 40,
    imagem: "./japao/trigo-integral.png",
    japones: true,
  },
  {
    id: "22",
    marca: "KitKat",
    nome: "Dark Chocolate",
    preco: 40,
    imagem: "./japao/dark-chocolate.png",
    japones: true,
  },
  {
    id: "23",
    marca: "KitKat",
    nome: "Uji Matcha",
    preco: 40,
    imagem: "./japao/uji-matcha.png",
    japones: true,
  },
  {
    id: "24",
    marca: "KitKat",
    nome: "Strawberry",
    preco: 40,
    imagem: "./japao/strawberry.png",
    japones: true,
  },
  {
    id: "25",
    marca: "KitKat",
    nome: "Chocolate Branco",
    preco: 40,
    imagem: "./japao/white-chocolate.png",
    japones: true,
  },
  {
    id: "26",
    marca: "KitKat",
    nome: "Raspberry",
    preco: 40,
    imagem: "./japao/raspberry.png",
    japones: true,
  },
  {
    id: "27",
    marca: "KitKat",
    nome: "Caramelo",
    preco: 40,
    imagem: "./japao/caramelo-derretido.png",
    japones: true,
  },
  {
    id: "28",
    marca: "KitKat",
    nome: "Inverno: Sorvete de Festa",
    preco: 40,
    imagem: "./japao/Winter Party Ice Cream.png",
    japones: true,
  },
  {
    id: "29",
    marca: "KitKat",
    nome: "Inverno: Morango com leite",
    preco: 40,
    imagem: "./japao/Winter Strawberry Milk.png",
    japones: true,
  },
  {
    id: "30",
    marca: "KitKat",
    nome: "Inverno: Morango Daifuku",
    preco: 40,
    imagem: "./japao/Winter Strawberry Daifuku.png",
    japones: true,
  },
  {
    id: "31",
    marca: "KitKat",
    nome: "Inverno: Morango Gateau Chocolat",
    preco: 40,
    imagem: "./japao/Winter Strawberry Gateau Chocolat.png",
    japones: true,
  },
  {
    id: "32",
    marca: "KitKat",
    nome: "Inverno: Chocolate Laranja",
    preco: 40,
    imagem: "./japao/Winter Orange Chocolate.png",
    japones: true,
  },
  {
    id: "33",
    marca: "KitKat",
    nome: "Inverno: Pistache",
    preco: 40,
    imagem: "./japao/Winter Pistachio.png",
    japones: true,
  },
  {
    id: "34",
    marca: "KitKat",
    nome: "Primavera: Sakura",
    preco: 40,
    imagem: "./japao/Spring Sakura.png",
    japones: true,
  },
  {
    id: "35",
    marca: "KitKat",
    nome: "Primavera: Sakura Mochi",
    preco: 40,
    imagem: "./japao/Spring Sakura Mochi.png",
    japones: true,
  },
  {
    id: "36",
    marca: "KitKat",
    nome: "Primavera: Sakura Sake",
    preco: 40,
    imagem: "./japao/Spring Sakura Sake.png",
    japones: true,
  },
  {
    id: "37",
    marca: "KitKat",
    nome: "Primavera: Sakura Kinako(Farofa de soja em pó)",
    preco: 40,
    imagem: "./japao/Spring Sakura Kinako.png",
    japones: true,
  },
  {
    id: "38",
    marca: "KitKat",
    nome: "Primavera: Sakura Matcha",
    preco: 40,
    imagem: "./japao/Spring Sakura Matcha.png",
    japones: true,
  },
  {
    id: "39",
    marca: "KitKat",
    nome: "Primavera: Pêssego",
    preco: 40,
    imagem: "./japao/Spring Peach.png",
    japones: true,
  },
  {
    id: "40",
    marca: "KitKat",
    nome: "Primavera: Pêssego Parfait",
    preco: 40,
    imagem: "./japao/Spring Peach Parfait.png",
    japones: true,
  },
  {
    id: "41",
    marca: "KitKat",
    nome: "Verão: Sal Oceânico",
    preco: 40,
    imagem: "./japao/Summer Ocean Salt.png",
    japones: true,
  },
  {
    id: "42",
    marca: "KitKat",
    nome: "Verão: Lichia Salgada",
    preco: 40,
    imagem: "./japao/Summer Salt Lychee.png",
    japones: true,
  },
  {
    id: "43",
    marca: "KitKat",
    nome: "Verão: Sal e Limão",
    preco: 40,
    imagem: "./japao/Summer Salt & Lemon.png",
    japones: true,
  },
  {
    id: "44",
    marca: "KitKat",
    nome: "Verão: Premium Mint",
    preco: 40,
    imagem: "./japao/Summer Premium Mint.png",
    japones: true,
  },
  {
    id: "45",
    marca: "KitKat",
    nome: "Verão: Sorvete de Verão",
    preco: 40,
    imagem: "./japao/Summer Summer Ice Cream.png",
    japones: true,
  },
  {
    id: "46",
    marca: "KitKat",
    nome: "Verão: Cookies e Sorvetes de Creme",
    preco: 40,
    imagem: "./japao/Summer Cookies & Cream Ice Cream.png",
    japones: true,
  },
  {
    id: "47",
    marca: "KitKat",
    nome: "Outono: Batata Doce",
    preco: 40,
    imagem: "./japao/Fall Sweet Potato.png",
    japones: true,
  },
  {
    id: "47",
    marca: "KitKat",
    nome: "Outono: Castanhas",
    preco: 40,
    imagem: "./japao/Fall Chestnuts.png",
    japones: true,
  },
  {
    id: "48",
    marca: "KitKat",
    nome: "Outono: Torta de Maçã",
    preco: 40,
    imagem: "./japao/Fall Apple Pie.png",
    japones: true,
  },
  {
    id: "49",
    marca: "KitKat",
    nome: "Outono: Fall Cafe Au’ Lait",
    preco: 40,
    imagem: "./japao/Fall Cafe Au’ Lait.png",
    japones: true,
  },
  {
    id: "50",
    marca: "KitKat",
    nome: "Outono: Mont Blanc",
    preco: 40,
    imagem: "./japao/Fall Mont Blanc.png",
    japones: true,
  },
  {
    id: "51",
    marca: "KitKat",
    nome: "Outono: Chá com Leite",
    preco: 40,
    imagem: "./japao/Fall Milk Tea.png",
    japones: true,
  },
  {
    id: "52",
    marca: "KitKat",
    nome: "Papai Noel de Natal",
    preco: 40,
    imagem: "./japao/Christmas Santa.png",
    japones: true,
  },
  {
    id: "53",
    marca: "KitKat",
    nome: "Chocolate de Ano Novo",
    preco: 40,
    imagem: "./japao/New Year’s Chocolate.png",
    japones: true,
  },
  {
    id: "54",
    marca: "KitKat",
    nome: "Otoshidama (dinheiro de presente em envelopes vermelhos.)",
    preco: 40,
    imagem: "./japao/Otoshidama.png",
    japones: true,
  },
  {
    id: "54",
    marca: "KitKat",
    nome: "Banana de Páscoa",
    preco: 40,
    imagem: "./japao/Easter Banana.png",
    japones: true,
  },
  {
    id: "55",
    marca: "KitKat",
    nome: "Urso de coração",
    preco: 40,
    imagem: "./japao/Heartful Bear.png",
    japones: true,
  },
  {
    id: "56",
    marca: "KitKat",
    nome: "Halloween clássico",
    preco: 40,
    imagem: "./japao/Classic Halloween.png",
    japones: true,
  },
  {
    id: "57",
    marca: "KitKat",
    nome: "Tóquio Banana",
    preco: 40,
    imagem: "./japao/Tokyo Banana.png",
    japones: true,
  },
  {
    id: "58",
    marca: "KitKat",
    nome: "Sorvete Choco Mint",
    preco: 40,
    imagem: "./japao/Choco Mint Ice Cream.png",
    japones: true,
  },
  {
    id: "59",
    marca: "KitKat",
    nome: "Suco de Vegetais",
    preco: 40,
    imagem: "./japao/Vegetable Juice.png",
    japones: true,
  },
  {
    id: "60",
    marca: "KitKat",
    nome: "Rilakkuma Bolos Quentes",
    preco: 40,
    imagem: "./japao/Rilakkuma Hotcakes.png",
    japones: true,
  },
  {
    id: "61",
    marca: "KitKat",
    nome: "Custard Pudding",
    preco: 40,
    imagem: "./japao/Custard Pudding.png",
    japones: true,
  },
  {
    id: "62",
    marca: "KitKat",
    nome: "Cheesecake",
    preco: 40,
    imagem: "./japao/Cheesecake.png",
    japones: true,
  },
  {
    id: "63",
    marca: "KitKat",
    nome: "Sweet Potato",
    preco: 40,
    imagem: "./japao/Sweet Potato.png",
    japones: true,
  },
  {
    id: "64",
    marca: "KitKat",
    nome: "Big Little Classic",
    preco: 40,
    imagem: "./japao/Big Little Classic.png",
    japones: true,
  },
  {
    id: "65",
    marca: "KitKat",
    nome: "Big Little Cacao",
    preco: 40,
    imagem: "./japao/Big Little Cacao.png",
    japones: true,
  },
  {
    id: "66",
    marca: "KitKat",
    nome: "Big Little Strawberry",
    preco: 40,
    imagem: "./japao/Big Little Strawberry.png",
    japones: true,
  },
  {
    id: "67",
    marca: "KitKat",
    nome: "Bit Little White",
    preco: 40,
    imagem: "./japao/Bit Little White.png",
    japones: true,
  },
  {
    id: "68",
    marca: "KitKat",
    nome: "Big Little Kumamon Green Tea",
    preco: 40,
    imagem: "./japao/Big Little Kumamon Green Tea.png",
    japones: true,
  },
  {
    id: "69",
    marca: "KitKat",
    nome: "Big Little Choco Banana",
    preco: 40,
    imagem: "./japao/Big Little Choco Banana.png",
    japones: true,
  },
  {
    id: "70",
    marca: "KitKat",
    nome: "Nuts & Cranberries",
    preco: 40,
    imagem: "./japao/Nuts & Cranberries.png",
    japones: true,
  },
  {
    id: "71",
    marca: "KitKat",
    nome: "Ruby Nuts & Cranberries",
    preco: 40,
    imagem: "./japao/Ruby Nuts & Cranberries.png",
    japones: true,
  },
  {
    id: "72",
    marca: "KitKat",
    nome: "Soymilk Nuts & Cranberries",
    preco: 40,
    imagem: "./japao/Soymilk Nuts & Cranberries.png",
    japones: true,
  },
  {
    id: "73",
    marca: "KitKat",
    nome: "Yogurt Nuts & Cranberries",
    preco: 40,
    imagem: "./japao/Yogurt Nuts & Cranberries.png",
    japones: true,
  },
  {
    id: "74",
    marca: "KitKat",
    nome: "Gunma Safari Maple",
    preco: 40,
    imagem: "./japao/Gunma Safari Maple.png",
    japones: true,
  },
  {
    id: "75",
    marca: "KitKat",
    nome: "Hiroshima Momiji Manju",
    preco: 40,
    imagem: "./japao/Hiroshima Momiji Manju.png",
    japones: true,
  },
  {
    id: "76",
    marca: "KitKat",
    nome: "Hokkaido Yubari Melon",
    preco: 40,
    imagem: "./japao/Hokkaido Yubari Melon.png",
    japones: true,
  },
  {
    id: "77",
    marca: "KitKat",
    nome: "Hokkaido Melon & Mascarpone Cheese",
    preco: 40,
    imagem: "./japao/Hokkaido Melon & Mascarpone Cheese.png",
    japones: true,
  },
  {
    id: "78",
    marca: "KitKat",
    nome: "Aomori Apple",
    preco: 40,
    imagem: "./japao/Aomori Apple.png",
    japones: true,
  },
  {
    id: "79",
    marca: "KitKat",
    nome: "Aomori Apple Pie",
    preco: 40,
    imagem: "./japao/Aomori Apple Pie.png",
    japones: true,
  },
  {
    id: "80",
    marca: "KitKat",
    nome: "Ehime Iyokan",
    preco: 40,
    imagem: "./japao/Ehime Iyokan.png",
    japones: true,
  },
  {
    id: "81",
    marca: "KitKat",
    nome: "Fukuoka Amaou Strawberry",
    preco: 40,
    imagem: "./japao/Fukuoka Amaou Strawberry.png",
    japones: true,
  },
  {
    id: "82",
    marca: "KitKat",
    nome: "Hyogo Kobe Pudding",
    preco: 40,
    imagem: "./japao/Hyogo Kobe Pudding.png",
    japones: true,
  },
  {
    id: "83",
    marca: "KitKat",
    nome: "Ibaraki Onsen Manju",
    preco: 40,
    imagem: "./japao/Ibaraki Onsen Manju.png",
    japones: true,
  },
  {
    id: "84",
    marca: "KitKat",
    nome: "Iwate Iwaizumi Yoghurt",
    preco: 40,
    imagem: "./japao/Iwate Iwaizumi Yoghurt.png",
    japones: true,
  },
  {
    id: "85",
    marca: "KitKat",
    nome: "Kanagawa Strawberry Cheesecake",
    preco: 40,
    imagem: "./japao/Kanagawa Strawberry Cheesecake.png",
    japones: true,
  },
  {
    id: "86",
    marca: "KitKat",
    nome: "Kumamoto Black Sugar Donuts",
    preco: 40,
    imagem: "./japao/Kumamoto Black Sugar Donuts.png",
    japones: true,
  },
  {
    id: "87",
    marca: "KitKat",
    nome: "Kumamoto Ikinari Dango",
    preco: 40,
    imagem: "./japao/Kumamoto Ikinari Dango.png",
    japones: true,
  },
  {
    id: "88",
    marca: "KitKat",
    nome: "Kyoto Kyoto Roasted Green Tea",
    preco: 40,
    imagem: "./japao/Kyoto Kyoto Roasted Green Tea.png",
    japones: true,
  },
  {
    id: "89",
    marca: "KitKat",
    nome: "Miyagi Zunda",
    preco: 40,
    imagem: "./japao/Miyagi Zunda.png",
    japones: true,
  },
  {
    id: "90",
    marca: "KitKat",
    nome: "Miyagi Zunda Shake",
    preco: 40,
    imagem: "./japao/Miyagi Zunda Shake.png",
    japones: true,
  },
  {
    id: "91",
    marca: "KitKat",
    nome: "Miyazaki Summer Mango",
    preco: 40,
    imagem: "./japao/Miyazaki Summer Mango.png",
    japones: true,
  },
  {
    id: "92",
    marca: "KitKat",
    nome: "Nagano Kyoho Grape",
    preco: 40,
    imagem: "./japao/Nagano Kyoho Grape.png",
    japones: true,
  },
  {
    id: "93",
    marca: "KitKat",
    nome: "Niigata Le Lectier",
    preco: 40,
    imagem: "./japao/Niigata Le Lectier.png",
    japones: true,
  },
  {
    id: "94",
    marca: "KitKat",
    nome: "Tochigi Tochiotome Strawberry",
    preco: 40,
    imagem: "./japao/Tochigi Tochiotome Strawberry.png",
    japones: true,
  },
  {
    id: "95",
    marca: "KitKat",
    nome: "Tokushima Peach",
    preco: 40,
    imagem: "./japao/Tokushima Peach.png",
    japones: true,
  },
  {
    id: "96",
    marca: "KitKat",
    nome: "Yamagata Cherry",
    preco: 40,
    imagem: "./japao/Yamagata Cherry.png",
    japones: true,
  },
  {
    id: "97",
    marca: "KitKat",
    nome: "Yokohama Harbor Marron",
    preco: 40,
    imagem: "./japao/Yokohama Harbor Marron.png",
    japones: true,
  },
  {
    id: "98",
    marca: "KitKat",
    nome: "Tokyo Island Lemon",
    preco: 40,
    imagem: "./japao/Tokyo Island Lemon.png",
    japones: true,
  },
  {
    id: "99",
    marca: "KitKat",
    nome: "Hokkaido Red Bean & Strawberry",
    preco: 40,
    imagem: "./japao/Hokkaido Red Bean & Strawberry.png",
    japones: true,
  },
  {
    id: "100",
    marca: "KitKat",
    nome: "Yokohama Strawberry Cheesecake",
    preco: 40,
    imagem: "./japao/Yokohama Strawberry Cheesecake.png",
    japones: true,
  },
  {
    id: "101",
    marca: "KitKat",
    nome: "Shizuoka Wasabi",
    preco: 40,
    imagem: "./japao/Shizuoka Wasabi.png",
    japones: true,
  },
  {
    id: "102",
    marca: "KitKat",
    nome: "Shinshu Shinshu Apples",
    preco: 40,
    imagem: "./japao/Shinshu Shinshu Apples.png",
    japones: true,
  },
  {
    id: "103",
    marca: "KitKat",
    nome: "Tokai Azuki Sando",
    preco: 40,
    imagem: "./japao/Tokai Azuki Sando.png",
    japones: true,
  },
  {
    id: "104",
    marca: "KitKat",
    nome: "Kyoto Ito Kyuemon Uji Matcha",
    preco: 40,
    imagem: "./japao/Kyoto Ito Kyuemon Uji Matcha.png",
    japones: true,
  },
  {
    id: "105",
    marca: "KitKat",
    nome: "Kyoto Ito Kyuemon Hojicha",
    preco: 40,
    imagem: "./japao/Kyoto Ito Kyuemon Hojicha.png",
    japones: true,
  },
  {
    id: "106",
    marca: "KitKat",
    nome: "Hiroshima Kotsudo Original Momiji Manju",
    preco: 40,
    imagem: "./japao/Hiroshima Kotsudo Original Momiji Manju.png",
    japones: true,
  },
  {
    id: "107",
    marca: "KitKat",
    nome: "Kyushu Amaou Strawberry",
    preco: 40,
    imagem: "./japao/Kyushu Amaou Strawberry.png",
    japones: true,
  },
  {
    id: "108",
    marca: "KitKat",
    nome: "Okinawa Beniimo",
    preco: 40,
    imagem: "./japao/Okinawa Beniimo.png",
    japones: true,
  },
  {
    id: "109",
    marca: "KitKat",
    nome: "Premium Japan Sake",
    preco: 40,
    imagem: "./japao/Premium Japan Sake.png",
    japones: true,
  },
  {
    id: "110",
    marca: "KitKat",
    nome: "Umeshi Sake",
    preco: 40,
    imagem: "./japao/Umeshi Sake.png",
    japones: true,
  },
  {
    id: "111",
    marca: "KitKat",
    nome: "Bijofu Yuzu Sake",
    preco: 40,
    imagem: "./japao/Bijofu Yuzu Sake.png",
    japones: true,
  },
  {
    id: "112",
    marca: "KitKat",
    nome: "Yogurt Sake",
    preco: 40,
    imagem: "./japao/Yogurt Sake.png",
    japones: true,
  },
  {
    id: "113",
    marca: "KitKat",
    nome: "Sakura Sake",
    preco: 40,
    imagem: "./japao/Sakura Sake.png",
    japones: true,
  },
  {
    id: "114",
    marca: "KitKat",
    nome: "Rum Raisin",
    preco: 40,
    imagem: "./japao/Rum Raisin.png",
    japones: true,
  },
  {
    id: "115",
    marca: "KitKat",
    nome: "Sublime Volcanic Papua New Guinea",
    preco: 40,
    imagem: "./japao/Sublime Volcanic Papua New Guinea.png",
    japones: true,
  },
  {
    id: "116",
    marca: "KitKat",
    nome: "Sublime Volcanic Vanuatu",
    preco: 40,
    imagem: "./japao/Sublime Volcanic Vanuatu.png",
    japones: true,
  },
  {
    id: "117",
    marca: "KitKat",
    nome: "Sublime Volcanic Philippines",
    preco: 40,
    imagem: "./japao/Sublime Volcanic Philippines.png",
    japones: true,
  },
  {
    id: "118",
    marca: "KitKat",
    nome: "Sublime Ruby",
    preco: 40,
    imagem: "./japao/Sublime Ruby.png",
    japones: true,
  },
  {
    id: "119",
    marca: "KitKat",
    nome: "Sublime Milk",
    preco: 40,
    imagem: "./japao/Sublime Milk.png",
    japones: true,
  },
  {
    id: "120",
    marca: "KitKat",
    nome: "Sublime Raw",
    preco: 40,
    imagem: "./japao/Sublime Raw.png",
    japones: true,
  },
  {
    id: "121",
    marca: "KitKat",
    nome: "Sublime Raw Bitter",
    preco: 40,
    imagem: "./japao/Sublime Raw Bitter.png",
    japones: true,
  },
  {
    id: "122",
    marca: "KitKat",
    nome: "Sublime Raw White",
    preco: 40,
    imagem: "./japao/Sublime Raw White.png",
    japones: true,
  },
  {
    id: "123",
    marca: "KitKat",
    nome: "Sublime Raw Matcha",
    preco: 40,
    imagem: "./japao/Sublime Raw Matcha.png",
    japones: true,
  },
  {
    id: "124",
    marca: "KitKat",
    nome: "Sublime Cacao Fruit",
    preco: 40,
    imagem: "./japao/Sublime Cacao Fruit.png",
    japones: true,
  },
  {
    id: "125",
    marca: "KitKat",
    nome: "Sublime Cassis",
    preco: 40,
    imagem: "./japao/Sublime Cassis.png",
    japones: true,
  },
  {
    id: "126",
    marca: "KitKat",
    nome: "Sublime Passionfruit",
    preco: 40,
    imagem: "./japao/Sublime Passionfruit.png",
    japones: true,
  },
  {
    id: "127",
    marca: "KitKat",
    nome: "Sublime Yuzu",
    preco: 40,
    imagem: "./japao/Sublime Yuzu.png",
    japones: true,
  },
  {
    id: "128",
    marca: "KitKat",
    nome: "Sublime Raspberry",
    preco: 40,
    imagem: "./japao/Sublime Raspberry.png",
    japones: true,
  },
  {
    id: "129",
    marca: "KitKat",
    nome: "Sublime Strawberry",
    preco: 40,
    imagem: "./japao/Sublime Strawberry.png",
    japones: true,
  },
  {
    id: "130",
    marca: "KitKat",
    nome: "Sublime Tasty in Frozen Passion Fruit",
    preco: 40,
    imagem: "./japao/Sublime Tasty in Frozen Passion Fruit.png",
    japones: true,
  },
  {
    id: "131",
    marca: "KitKat",
    nome: "Sublime Tasty in Frozen Raspberry",
    preco: 40,
    imagem: "./japao/Sublime Tasty in Frozen Raspberry.png",
    japones: true,
  },
  {
    id: "132",
    marca: "KitKat",
    nome: "Sublime Moleson",
    preco: 40,
    imagem: "./japao/Sublime Moleson.png",
    japones: true,
  },
  {
    id: "133",
    marca: "KitKat",
    nome: "Special Strawberry Maple",
    preco: 40,
    imagem: "./japao/Special Strawberry Maple.png",
    japones: true,
  },
  {
    id: "134",
    marca: "KitKat",
    nome: "Special Matcha Kinako",
    preco: 40,
    imagem: "./japao/Special Matcha Kinako.png",
    japones: true,
  },
  {
    id: "135",
    marca: "KitKat",
    nome: "Special Orange Cocktail",
    preco: 40,
    imagem: "./japao/Special Orange Cocktail.png",
    japones: true,
  },
  {
    id: "136",
    marca: "KitKat",
    nome: "Special Ginger",
    preco: 40,
    imagem: "./japao/Special Ginger.png",
    japones: true,
  },
  {
    id: "137",
    marca: "KitKat",
    nome: "Special Cream Cheese",
    preco: 40,
    imagem: "./japao/Special Cream Cheese.png",
    japones: true,
  },
  {
    id: "138",
    marca: "KitKat",
    nome: "Special Plum",
    preco: 40,
    imagem: "./japao/Special Plum.png",
    japones: true,
  },
  {
    id: "139",
    marca: "KitKat",
    nome: "Special Butter",
    preco: 40,
    imagem: "./japao/Special Butter.png",
    japones: true,
  },
  {
    id: "140",
    marca: "KitKat",
    nome: "Gyokuro",
    preco: 40,
    imagem: "./japao/Gyokuro.png",
    japones: true,
  },
  {
    id: "141",
    marca: "KitKat",
    nome: "Kocha",
    preco: 40,
    imagem: "./japao/Kocha.png",
    japones: true,
  },
  {
    id: "142",
    marca: "KitKat",
    nome: "Oolong Kit Kat",
    preco: 40,
    imagem: "./japao/Oolong Kit Kat.png",
    japones: true,
  },
  {
    id: "143",
    marca: "KitKat",
    nome: "Hojicha",
    preco: 40,
    imagem: "./japao/Hojicha.png",
    japones: true,
  },
  {
    id: "144",
    marca: "KitKat",
    nome: "Hojicha",
    preco: 40,
    imagem: "./japao/Hojicha.png",
    japones: true,
  },
  {
    id: "145",
    marca: "KitKat",
    nome: "Examination Kit Kat",
    preco: 40,
    imagem: "./japao/Examination Kit Kat.png",
    japones: true,
  },
  {
    id: "146",
    marca: "KitKat",
    nome: "Kit Kat Mail",
    preco: 40,
    imagem: "./japao/Kit Kat Mail.png",
    japones: true,
  },
  {
    id: "147",
    marca: "KitKat",
    nome: "Cafe Latte",
    preco: 40,
    imagem: "./japao/Cafe Latte.png",
    japones: true,
  },
  {
    id: "148",
    marca: "KitKat",
    nome: "Yokubari Double",
    preco: 40,
    imagem: "./japao/Yokubari Double.png",
    japones: true,
  },
  {
    id: "149",
    marca: "KitKat",
    nome: "Yuzu Matcha",
    preco: 40,
    imagem: "./japao/Yuzu Matcha.png",
    japones: true,
  },
  {
    id: "150",
    marca: "KitKat",
    nome: "Mount Fuji Kit Kat",
    preco: 40,
    imagem: "./japao/Mount Fuji Kit Kat.png",
    japones: true,
  },
  {
    id: "151",
    marca: "KitKat",
    nome: "Cough Drop Kit Kats",
    preco: 40,
    imagem: "./japao/Cough Drop Kit Kats.png",
    japones: true,
  },
  {
    id: "152",
    marca: "KitKat",
    nome: "Strawberry & Tiramisu",
    preco: 40,
    imagem: "./japao/Strawberry & Tiramisu.png",
    japones: true,
  },
  {
    id: "153",
    marca: "KitKat",
    nome: "Soy Sauce",
    preco: 40,
    imagem: "./japao/Soy Sauce.png",
    japones: true,
  },
  {
    id: "154",
    marca: "KitKat",
    nome: "Hot Shinsu Chili",
    preco: 40,
    imagem: "./japao/Hot Shinsu Chili.png",
    japones: true,
  },
  {
    id: "155",
    marca: "KitKat",
    nome: "Apple Vinegar",
    preco: 40,
    imagem: "./japao/Apple Vinegar.png",
    japones: true,
  },
  {
    id: "156",
    marca: "KitKat",
    nome: "Ginger Ale",
    preco: 40,
    imagem: "./japao/Ginger Ale.png",
    japones: true,
  },
  {
    id: "157",
    marca: "KitKat",
    nome: "Royal Milk Tea",
    preco: 40,
    imagem: "./japao/Royal Milk Tea.png",
    japones: true,
  },
  {
    id: "158",
    marca: "KitKat",
    nome: "Pineapple",
    preco: 40,
    imagem: "./japao/Pineapple.png",
    japones: true,
  },
  {
    id: "159",
    marca: "KitKat",
    nome: "Kinako Ohagi",
    preco: 40,
    imagem: "./japao/Kinako Ohagi.png",
    japones: true,
  },
  {
    id: "160",
    marca: "KitKat",
    nome: "Origami Kit Kat",
    preco: 40,
    imagem: "./japao/Origami Kit Kat.png",
    japones: true,
  },
  {
    id: "161",
    marca: "KitKat",
    nome: "Caramel Pudding",
    preco: 40,
    imagem: "./japao/Caramel Pudding.png",
    japones: true,
  },
  {
    id: "162",
    marca: "KitKat",
    nome: "Matcha Latte",
    preco: 40,
    imagem: "./japao/Matcha Latte.png",
    japones: true,
  },
  {
    id: "163",
    marca: "KitKat",
    nome: "Chocolate Bar - Fragrant Coffee",
    preco: 40,
    imagem: "./japao/Chocolate Bar - Fragrant Coffee.png",
    japones: true,
  },
  {
    id: "164",
    marca: "KitKat",
    nome: "Premium Chocolates - Sachertorte",
    preco: 40,
    imagem: "./japao/Premium Chocolates - Sachertorte.png",
    japones: true,
  },
  {
    id: "165",
    marca: "KitKat",
    nome: "Chocolate Pouch Pack - Little Milk & White",
    preco: 40,
    imagem: "./japao/Chocolate Pouch Pack - Little Milk & White.png",
    japones: true,
  },
  {
    id: "166",
    marca: "KitKat",
    nome: "White With Salt",
    preco: 40,
    imagem: "./japao/White With Salt.png",
    japones: true,
  },
  {
    id: "167",
    marca: "KitKat",
    nome: "Chocolate Pouch Pack - Little Strawberry",
    preco: 40,
    imagem: "./japao/Chocolate Pouch Pack - Little Strawberry.png",
    japones: true,
  },
  {
    id: "168",
    marca: "KitKat",
    nome: "Chocolate Pouch Pack",
    preco: 40,
    imagem: "./japao/Chocolate Pouch Pack.png",
    japones: true,
  },
  {
    id: "169",
    marca: "KitKat",
    nome: "Chocolate Pouch Pack - Whole High Cacao",
    preco: 40,
    imagem: "./japao/Chocolate Pouch Pack - Whole High Cacao.png",
    japones: true,
  },
  {
    id: "170",
    marca: "KitKat",
    nome: "Chocolate Pouch Pack - Whole Wheat Biscuits",
    preco: 40,
    imagem: "./japao/Chocolate Pouch Pack - Whole Wheat Biscuits.png",
    japones: true,
  },
  {
    id: "171",
    marca: "KitKat",
    nome: "Halloween Break Chocolates - Apple Cinnamon",
    preco: 40,
    imagem: "./japao/Halloween Break Chocolates - Apple Cinnamon.png",
    japones: true,
  },
  {
    id: "172",
    marca: "KitKat",
    nome: "Chocolates - For Coffee Break",
    preco: 40,
    imagem: "./japao/Chocolates - For Coffee Break.png",
    japones: true,
  },
  {
    id: "173",
    marca: "KitKat",
    nome: "Earth Day Chocolates - Maple",
    preco: 40,
    imagem: "./japao/Earth Day Chocolates - Maple.png",
    japones: true,
  },
  {
    id: "174",
    marca: "KitKat",
    nome: "Snax - Cheese Soy & Salt Almond",
    preco: 40,
    imagem: "./japao/Snax - Cheese Soy & Salt Almond.png",
    japones: true,
  },
  {
    id: "175",
    marca: "KitKat",
    nome: "Chocolates - Ruby Almond And Cranberry",
    preco: 40,
    imagem: "./japao/Chocolates - Ruby Almond And Cranberry.png",
    japones: true,
  },
  {
    id: "176",
    marca: "KitKat",
    nome: "Chocolates - Banana Caramel",
    preco: 40,
    imagem: "./japao/Chocolates - Banana Caramel.png",
    japones: true,
  },
  {
    id: "177",
    marca: "KitKat",
    nome: "Dream Daruma Milk & Dark Chocolates",
    preco: 40,
    imagem: "./japao/Dream Daruma Milk & Dark Chocolates.png",
    japones: true,
  },
  {
    id: "178",
    marca: "KitKat",
    nome: "Support Message Pack",
    preco: 40,
    imagem: "./japao/Support Message Pack.png",
    japones: true,
  },
  {
    id: "179",
    marca: "KitKat",
    nome: "Passion Fruit",
    preco: 40,
    imagem: "./japao/Passion Fruit.png",
    japones: true,
  },
  {
    id: "180",
    marca: "KitKat",
    nome: "Shinsu Apple",
    preco: 40,
    imagem: "./japao/Shinsu Apple.png",
    japones: true,
  },
  {
    id: "181",
    marca: "KitKat",
    nome: "Japanese Plum",
    preco: 40,
    imagem: "./japao/Japanese Plum.png",
    japones: true,
  },
  {
    id: "182",
    marca: "KitKat",
    nome: "Sparkling Wine",
    preco: 40,
    imagem: "./japao/Sparkling Wine.png",
    japones: true,
  },
  {
    id: "183",
    marca: "KitKat",
    nome: "Onsen Manjyu",
    preco: 40,
    imagem: "./japao/Onsen Manjyu.png",
    japones: true,
  },
  {
    id: "184",
    marca: "KitKat",
    nome: "Japanese Cheesecake",
    preco: 40,
    imagem: "./japao/Japanese Cheesecake.png",
    japones: true,
  },
  {
    id: "185",
    marca: "KitKat",
    nome: "Nuts & Cranberry",
    preco: 40,
    imagem: "./japao/Nuts & Cranberry.png",
    japones: true,
  },
  {
    id: "186",
    marca: "KitKat",
    nome: "Frozen Cookies & Cream",
    preco: 40,
    imagem: "./japao/Frozen Cookies & Cream.png",
    japones: true,
  },
  {
    id: "187",
    marca: "KitKat",
    nome: "Frozen Strawberry Cheesecake",
    preco: 40,
    imagem: "./japao/Frozen Strawberry Cheesecake.png",
    japones: true,
  },
  {
    id: "188",
    marca: "KitKat",
    nome: "Blueberry",
    preco: 40,
    imagem: "./japao/Blueberry.png",
    japones: true,
  },
  {
    id: "189",
    marca: "KitKat",
    nome: "Lemon Cheese Cake",
    preco: 40,
    imagem: "./japao/Lemon Cheese Cake.png",
    japones: true,
  },
  {
    id: "190",
    marca: "KitKat",
    nome: "Blood Orange",
    preco: 40,
    imagem: "./japao/Blood Orange.png",
    japones: true,
  },
  {
    id: "191",
    marca: "KitKat",
    nome: "Muscat of Alexandria",
    preco: 40,
    imagem: "./japao/Muscat of Alexandria.png",
    japones: true,
  },
  {
    id: "192",
    marca: "KitKat",
    nome: "Fruit Parfait",
    preco: 40,
    imagem: "./japao/Fruit Parfait.png",
    japones: true,
  },
  {
    id: "193",
    marca: "KitKat",
    nome: "Sweet Red-Bean Soup",
    preco: 40,
    imagem: "./japao/Sweet Red-Bean Soup.png",
    japones: true,
  },
  {
    id: "194",
    marca: "KitKat",
    nome: "Cherry Blossom",
    preco: 40,
    imagem: "./japao/Cherry Blossom.png",
    japones: true,
  },
  {
    id: "195",
    marca: "KitKat",
    nome: "Green Tea and Cherry Blossom",
    preco: 40,
    imagem: "./japao/Green Tea and Cherry Blossom.png",
    japones: true,
  },
  {
    id: "196",
    marca: "KitKat",
    nome: "Gold Peach and white peach",
    preco: 40,
    imagem: "./japao/Gold Peach and white peach.png",
    japones: true,
  },
  {
    id: "197",
    marca: "KitKat",
    nome: "Jasmine Tea",
    preco: 40,
    imagem: "./japao/Jasmine Tea.png",
    japones: true,
  },
  {
    id: "198",
    marca: "KitKat",
    nome: "Tiramisu",
    preco: 40,
    imagem: "./japao/Tiramisu.png",
    japones: true,
  },
  {
    id: "199",
    marca: "KitKat",
    nome: "Cola and Lemon Squash",
    preco: 40,
    imagem: "./japao/Cola and Lemon Squash.png",
    japones: true,
  },
  {
    id: "200",
    marca: "KitKat",
    nome: "Vanilla Ice",
    preco: 40,
    imagem: "./japao/Vanilla Ice.png",
    japones: true,
  },
  {
    id: "201",
    marca: "KitKat",
    nome: "Aloe Yogurt",
    preco: 40,
    imagem: "./japao/Aloe Yogurt.png",
    japones: true,
  },
  {
    id: "202",
    marca: "KitKat",
    nome: "Triple Chocolate",
    preco: 40,
    imagem: "./japao/Triple Chocolate.png",
    japones: true,
  },
  {
    id: "203",
    marca: "KitKat",
    nome: "Sour Orange",
    preco: 40,
    imagem: "./japao/Sour Orange.png",
    japones: true,
  },
  {
    id: "204",
    marca: "KitKat",
    nome: "Kiwi",
    preco: 40,
    imagem: "./japao/Kiwi.png",
    japones: true,
  },
  {
    id: "205",
    marca: "KitKat",
    nome: "Takagi White Brittany Milk",
    preco: 40,
    imagem: "./japao/Takagi White Brittany Milk.png",
    japones: true,
  },
  {
    id: "206",
    marca: "KitKat",
    nome: "Apricot Jelly",
    preco: 40,
    imagem: "./japao/Apricot Jelly.png",
    japones: true,
  },
  {
    id: "207",
    marca: "KitKat",
    nome: "University Potato",
    preco: 40,
    imagem: "./japao/University Potato.png",
    japones: true,
  },
  {
    id: "208",
    marca: "KitKat",
    nome: "Pumpkin Pudding",
    preco: 40,
    imagem: "./japao/Pumpkin Pudding.png",
    japones: true,
  },
  {
    id: "209",
    marca: "KitKat",
    nome: "Pumpkin Cheesecake",
    preco: 40,
    imagem: "./japao/Pumpkin Cheesecake.png",
    japones: true,
  },
  {
    id: "210",
    marca: "KitKat",
    nome: "Hokkaido Grilled Corn",
    preco: 40,
    imagem: "./japao/Hokkaido Grilled Corn.png",
    japones: true,
  },
  {
    id: "211",
    marca: "KitKat",
    nome: "Hokkaido Potato",
    preco: 40,
    imagem: "./japao/Hokkaido Potato.png",
    japones: true,
  },
  {
    id: "212",
    marca: "KitKat",
    nome: "Sports Drink",
    preco: 40,
    imagem: "./japao/Sports Drink.png",
    japones: true,
  },
  {
    id: "213",
    marca: "KitKat",
    nome: "Ramune (Soda Pop)",
    preco: 40,
    imagem: "./japao/Ramune (Soda Pop).png",
    japones: true,
  },
  {
    id: "214",
    marca: "KitKat",
    nome: "Calpis",
    preco: 40,
    imagem: "./japao/Calpis.png",
    japones: true,
  },
  {
    id: "215",
    marca: "KitKat",
    nome: "Caramel Macchiato",
    preco: 40,
    imagem: "./japao/Caramel Macchiato.png",
    japones: true,
  },
  {
    id: "216",
    marca: "KitKat",
    nome: "Watermelon",
    preco: 40,
    imagem: "./japao/Watermelon.png",
    japones: true,
  },
  {
    id: "217",
    marca: "KitKat",
    nome: "Caramel and Vanilla",
    preco: 40,
    imagem: "./japao/Caramel and Vanilla.png",
    japones: true,
  },
  {
    id: "218",
    marca: "KitKat",
    nome: "Vanilla Beans",
    preco: 40,
    imagem: "./japao/Vanilla Beans.png",
    japones: true,
  },
  {
    id: "219",
    marca: "KitKat",
    nome: "Espresso Coffee",
    preco: 40,
    imagem: "./japao/Espresso Coffee.png",
    japones: true,
  },
  {
    id: "220",
    marca: "KitKat",
    nome: "Matcha Tiramisu",
    preco: 40,
    imagem: "./japao/Matcha Tiramisu.png",
    japones: true,
  },
  {
    id: "221",
    marca: "KitKat",
    nome: "Choco and Rose",
    preco: 40,
    imagem: "./japao/Choco and Rose.png",
    japones: true,
  },
  {
    id: "222",
    marca: "KitKat",
    nome: "Mild Bitter",
    preco: 40,
    imagem: "./japao/Mild Bitter.png",
    japones: true,
  },
  {
    id: "223",
    marca: "KitKat",
    nome: "Gigantic Grapes",
    preco: 40,
    imagem: "./japao/Gigantic Grapes.png",
    japones: true,
  },
  {
    id: "224",
    marca: "KitKat",
    nome: "Yukimi Cherry",
    preco: 40,
    imagem: "./japao/Yukimi Cherry.png",
    japones: true,
  },
  {
    id: "225",
    marca: "KitKat",
    nome: "Cacao 61%",
    preco: 40,
    imagem: "./japao/Cacao 61.png",
    japones: true,
  },
  {
    id: "226",
    marca: "KitKat",
    nome: "Wine",
    preco: 40,
    imagem: "./japao/Wine.png",
    japones: true,
  },
  {
    id: "227",
    marca: "KitKat",
    nome: "Noir",
    preco: 40,
    imagem: "./japao/Noir.png",
    japones: true,
  },
  {
    id: "228",
    marca: "KitKat",
    nome: "Unshiu Orange",
    preco: 40,
    imagem: "./japao/Unshiu Orange.png",
    japones: true,
  },
  {
    id: "229",
    marca: "KitKat",
    nome: "Brown Sugar",
    preco: 40,
    imagem: "./japao/Brown Sugar.png",
    japones: true,
  },
  {
    id: "230",
    marca: "KitKat",
    nome: "Brown Sugar Kinako",
    preco: 40,
    imagem: "./japao/Brown Sugar Kinako.png",
    japones: true,
  },
  {
    id: "231",
    marca: "KitKat",
    nome: "Bitter Almond",
    preco: 40,
    imagem: "./japao/Bitter Almond.png",
    japones: true,
  },
  {
    id: "232",
    marca: "KitKat",
    nome: "Cocoa",
    preco: 40,
    imagem: "./japao/Cocoa.png",
    japones: true,
  },
  {
    id: "233",
    marca: "KitKat",
    nome: "Salted Vanilla",
    preco: 40,
    imagem: "./japao/Salted Vanilla.png",
    japones: true,
  },
  {
    id: "234",
    marca: "KitKat",
    nome: "Lucky Little",
    preco: 40,
    imagem: "./japao/Lucky Little.png",
    japones: true,
  },
  {
    id: "235",
    marca: "KitKat",
    nome: "Choco and Mango Pudding",
    preco: 40,
    imagem: "./japao/Choco and Mango Pudding.png",
    japones: true,
  },
  {
    id: "236",
    marca: "KitKat",
    nome: "Strawberry Cake",
    preco: 40,
    imagem: "./japao/Strawberry Cake.png",
    japones: true,
  },
  {
    id: "237",
    marca: "KitKat",
    nome: "Semi Sweet",
    preco: 40,
    imagem: "./japao/Semi Sweet.png",
    japones: true,
  },
  {
    id: "238",
    marca: "KitKat",
    nome: "Triple Berry",
    preco: 40,
    imagem: "./japao/Triple Berry.png",
    japones: true,
  },
  {
    id: "239",
    marca: "KitKat",
    nome: "Double Berry",
    preco: 40,
    imagem: "./japao/Double Berry.png",
    japones: true,
  },
  {
    id: "240",
    marca: "KitKat",
    nome: "Ice Stick",
    preco: 40,
    imagem: "./japao/Ice Stick.png",
    japones: true,
  },
  {
    id: "241",
    marca: "KitKat",
    nome: "Apricot Dessert Flavor",
    preco: 40,
    imagem: "./japao/Apricot Dessert Flavor.png",
    japones: true,
  },
  {
    id: "242",
    marca: "KitKat",
    nome: "Yogurt Dressing",
    preco: 40,
    imagem: "./japao/Yogurt Dressing.png",
    japones: true,
  },
  {
    id: "243",
    marca: "KitKat",
    nome: "Cheese",
    preco: 40,
    imagem: "./japao/Cheese.png",
    japones: true,
  },
  {
    id: "244",
    marca: "KitKat",
    nome: "Raspberry and Passion Fruit",
    preco: 40,
    imagem: "./japao/Raspberry and Passion Fruit.png",
    japones: true,
  },
  {
    id: "245",
    marca: "KitKat",
    nome: "Caramac",
    preco: 40,
    imagem: "./japao/Caramac.png",
    japones: true,
  },
  {
    id: "246",
    marca: "KitKat",
    nome: "Strawberry Fromage",
    preco: 40,
    imagem: "./japao/Strawberry Fromage.png",
    japones: true,
  },
  {
    id: "247",
    marca: "KitKat",
    nome: "Blueberry Fromage",
    preco: 40,
    imagem: "./japao/Blueberry Fromage.png",
    japones: true,
  },
  {
    id: "248",
    marca: "KitKat",
    nome: "Miso (Soybean Paste)",
    preco: 40,
    imagem: "./japao/Miso (Soybean Paste).png",
    japones: true,
  },
  {
    id: "249",
    marca: "KitKat",
    nome: "Ichimi (Spicy)",
    preco: 40,
    imagem: "./japao/Ichimi (Spicy).png",
    japones: true,
  },
  {
    id: "250",
    marca: "KitKat",
    nome: "Beniimo",
    preco: 40,
    imagem: "./japao/Beniimo.png",
    japones: true,
  },
  {
    id: "251",
    marca: "KitKat",
    nome: "Tokyo Rum Raisin",
    preco: 40,
    imagem: "./japao/Tokyo Rum Raisin.png",
    japones: true,
  },
  {
    id: "252",
    marca: "KitKat",
    nome: "Yuzu and Pepper",
    preco: 40,
    imagem: "./japao/Yuzu and Pepper.png",
    japones: true,
  },
];

export function salvarLocalStorage(chave, informacao) {
  localStorage.setItem(chave, JSON.stringify(informacao));
}

export function lerLocalStorage(chave) {
  return JSON.parse(localStorage.getItem(chave));
}

export function apagarDoLocalStorage(chave) {
  localStorage.removeItem(chave);
}

export function desenharProdutoCarrinhoSimples(
  idProduto,
  idContainerHtml,
  quantidadeProduto
) {
  const produto = catalogo.find((p) => p.id === idProduto);
  const containerProdutosCarrinho = document.getElementById(idContainerHtml);

  const elementoArticle = document.createElement("article"); //<article></article>
  const articleClasses = [
    "flex",
    "bg-stone-200",
    "rounded-lg",
    "p-1",
    "relative",
    "mb-2",
    "w-96",
  ];

  for (const articleClass of articleClasses) {
    elementoArticle.classList.add(articleClass);
  }
  //<article class="flex bg-slate-100 rounded-lg p-1 relative"></article>

  const cartaoProdutoCarrinho = `
    <img
      src="./assets/img/${produto.imagem}"
      alt="Carrinho: ${produto.nome}"
      class="h-24 rounded-lg"
    />
    <div class="p-2 flex flex-col justify-between">
      <p class="text-slate-900  text-sm">
        ${produto.nome}
      </p>
      <p class="text-slate-400 text-xs">KitKat: 🍫</p>
      <p class="text-green-700 text-lg">$${produto.preco}</p>
    </div>
    <div class='flex text-slate-950  items-end absolute bottom-0 right-2 text-lg'>
        <p id='quantidade-${produto.id}' class='ml-2'>${quantidadeProduto}</p>
    </div>`;
  //<article class="flex bg-slate-100 rounded-lg p-1 relative">codigo do cartao do produto</article>

  elementoArticle.innerHTML = cartaoProdutoCarrinho;
  containerProdutosCarrinho.appendChild(elementoArticle);
}
